[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed custom model validator

(cherry picked from commit 1ba6f7b7532a7167b2e3b5245bff7000bd91f2e0)

IJ-CR-21961

GitOrigin-RevId: e38e0fdf125a068c9e6eb7a8e84ac98060aa78d1