IJP-1342: Do not invalidate PSI on file move. Only invalidate PSI on language level change (be it caused by move or not)
This also fixes test: org.angular2.refactoring.MoveTest.testFolderDotBaseRelative
```
ERROR: Psi file was invalidated after move file: '/src/src/app/dest/test1/app1.component.ts'. All file references will be lost
java.lang.Throwable: Psi file was invalidated after move file: '/src/src/app/dest/test1/app1.component.ts'. All file references will be lost
	at com.intellij.openapi.diagnostic.Logger.error
	at com.intellij.lang.typescript.refactoring.ES6MoveFileHandler.retargetUsages
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesProcessor.performRefactoringInBranch
	...
```

GitOrigin-RevId: 7df6ac2dabc8c8e2e48b82e1f60d400e9cfd6bd0