IDEA-248287: restore binary compatibility of InlayHintsSink
Changes introduced in 9cc136f09840c7c772ce4abf1c8f59b55994907b break binary compatibility of `InlayHintsSink` class.
It leads to `NoSuchMethodError` for plugins built with 2020.2 platform and installed on 2020.3

GitOrigin-RevId: 66a2301b3938e244e518bd78151dc033c5778a7f