[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed role hint

(cherry picked from commit bbc5bc5d8116179005930786bc246db11eada6a4)

IJ-CR-21961

GitOrigin-RevId: 09d32b5e88a1e581fc360a0eef8930db771ba580