git: fix handling of "Remove-Deleted" files
Changes to be committed:
        renamed:    A.txt -> B.txt
Changes not staged for commit:
        deleted:    B.txt

Such changes should be merged into A.txt deletion, rather than B.txt deletion.
This fixes an error on attempt to revert such changes from IDE:

git checkout HEAD -- B.txt
error: pathspec 'B.txt' did not match any file(s) known to git