[JEWEL-1263] Fix NoClassDefFoundError for JNA in standalone artifact
'net.java.dev.jna:jna' was used by 'StandalonePlatformCursorController'
but missing from the 'jewel-int-ui-standalone' POM, causing a
'NoClassDefFoundError: com/sun/jna/Library' at runtime whenever
'IntUiTheme' was composed.

Signed-off-by: Nebojsa.Vuksic <nebojsa.vuksic@jetbrains.com>

closes https://github.com/JetBrains/intellij-community/pull/3436

(cherry picked from commit 42c3908fd1a30eb4340e6f8c01f36b910286fd5e)


(cherry picked from commit 14ff575322c6117e9da0e24fcad403a37df3ffbd)

IJ-MR-193915

GitOrigin-RevId: e716551b90a1953fca5fcfddd6e6021a12666e19