com.intellij.diagnostic.PluginException: The default implementation of method 'getActionUpdateThread' is deprecated
GitOrigin-RevId: 23349b3c882cc96cd1f0d0fadb8eb7ab2a3aa611