IDEA-253386: NoClassDefFoundError fixed when pasting in editor
(cherry picked from commit 3715c1840d8fb2f2869fe2fe3792d72366cea9f4)

IJ-CR-3669

GitOrigin-RevId: 10893180b274ae081683a2c0cce40a3b84214026