[Gradle|Exec] new: introduce API for the simple reflective calling of removed setters and getters in Gradle API
This API ignores all reflection method access exception, because we can identify in which Gradle version this public API was removed.

### Issues
  * IDEA-369597 Cannot debug test with gradle. NoSuchMethodError: org.gradle.api.tasks.testing.Test.setForkEvery

GitOrigin-RevId: 069ed7531f58751c56ab91d1c3483facd0c041eb