PY-56370 No plots with Matplotlib 3.6.0: `AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
Add dummy support for the new pyplot API

(cherry picked from commit a57cfa1a3cd05b211f02eb22bb703fa5ad72404a)

IJ-CR-95901

GitOrigin-RevId: 5fcdce3dd99d9626cbe70f8e409c6093c3af947b