(IDEA-271142) JUnit5MalformedParameterized inspection moved to junit module (NoClassDefFoundError fixed)
GitOrigin-RevId: 4ff66cb6481e9fab4cceeca535616a984350aebf