CPP-22344: DaemonProcessRuntimeClasspath: Add kotlin-stdlib-jdk[78].jar
At this point, both are added just in case, after spending some time
investigating a hard to debug resource leak that turned out to be
caused by a NoClassDefFoundError from a (now gone) piece of code
performing `AutoCloseable.use { ... }`.

GitOrigin-RevId: a4f4e1459e290a92fbd22828bedc23b07ac3db7a