[fleet analyzer] fix `UnsupportedOperationException: no path here`
caused by debug logging in `PsiFileImpl.loadTreeElement`:

```
java.lang.UnsupportedOperationException: no path here
	at fleet.analyzer.filesystem.FileIdVirtualFile.getPath(FileIdVirtualFile.kt:61)
	at com.intellij.openapi.vfs.VirtualFile.getPresentableUrl(VirtualFile.java:197)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:232)
	...
```

GitOrigin-RevId: e07302f4a9a7d21e93ded2dd7270acb632fa0e64