tests: move dependency on KotlinPlugin library after dependencies on the platform
This is needed to ensure that platform classes won't load classes from KotlinPlugin, otherwise we may get errors while running tests (e.g. we got NoSuchMethodError because the platform and KotlinPlugin use different versions of kotlinx-coroutines-core library).