IJPL-149248: Add the missing dependency to intellij.libraries.grpc.netty.shaded module
NettyChannelProvider from intellij.libraries.grpc.netty.shaded is a subclass of ManagedChannelProvider from intellij.libraries.grpc
Without this fix, PluginException: Cannot load class io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider is thrown caused by NoClassDefFoundError: io/grpc/ManagedChannelProvider.


(cherry picked from commit 11881a7c425ba959119ab4280ba067b305f4f803)

IJ-CR-139675

GitOrigin-RevId: dbd2a69b3201fbd3b978c0c25d3a8fd79f538f2a