io.netty.handler.codec.TooLongFrameException: HTTP content length exceeded 1048576 bytes. (cherry picked from commit 651d2790aa96aea11ed65e1ad4808896b655d28e)