PY-61228: Fix WSL path browser: we do not browse removable drives
``rootDirectories`` returns all root drives including CD, flash, redirected and other removables.

Since some of them can't be accessed using NIO (i.e there is no ``.iso`` file in virtual CD drive of VM) tests might fail:

```
Wrong number of roots: [\\wsl$\Ubuntu-20.04\, C:\, D:\], while root drives are: [C:\, D:\, E:\] expected:<4> but was:<3>
```

But there is no reason to show such disks in any case because they are either readonly or too slow to be used as project storage.

``listWindowsRoots`` skip them

Merge-request: IJ-MR-109023
Merged-by: Ilya Kazakevich <ilya.kazakevich@jetbrains.com>

GitOrigin-RevId: 2c1fba6e819ed3c434566e5b3d76ffb1d57142a6