do not call `addProcessListener` in `BaseProcessHandler` constructor as it can be overridden in inheritors
For example, it leads to the following NPE:
java.lang.NullPointerException: Cannot enter synchronized block because "this.myEventsToResend" is null
	at com.intellij.lang.javascript.flow.ResendingOSProcessHandler.addProcessListener(ResendingOSProcessHandler.java:63)
	at com.intellij.execution.process.BaseProcessHandler.<init>(BaseProcessHandler.java:38)
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:31)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.lang.javascript.flow.ResendingOSProcessHandler.<init>(ResendingOSProcessHandler.java:27)
	at com.intellij.lang.javascript.flow.protocol.FlowJSStandardOutputProtocol.connect(FlowJSStandardOutputProtocol.java:70)
	at com.intellij.lang.javascript.service.JSLanguageServiceExecutorImpl.createProcessHandler(JSLanguageServiceExecutorImpl.java:174)

GitOrigin-RevId: c0ffc734e2f7d5e3d9998129b24d9b1faaba676b