IJPL-149087 %createJavaFile and %createKotlinFile commands fail due to 'NoClassDefFoundError: com/intellij/openapi/vcs/ex/ProjectLevelVcsManagerEx'
GitOrigin-RevId: ff13594a93fbe0f9f60461f4351430996a5a5ed3