DBE-25852: fixed Exception in thread "DefaultDispatcher-worker-33" java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/config/GradleFileTypeKt                  	at com.intellij.gradle.java.groovy.codeInspection.suppression.GradleGroovyTrafficLightRendererContributor.createRenderer(GradleGroovyTrafficLightRendererContributor.kt:19)                  	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManagerKt.createRenderer(ErrorStripeUpdateManager.kt:208)                  	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManagerKt.setTrafficLightOnEditorIfNeeded(ErrorStripeUpdateManager.kt:184)                  	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManagerKt.access$setTrafficLightOnEditorIfNeeded(ErrorStripeUpdateManager.kt:1)                  	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManager.asyncRepaintErrorStripePanel$intellij_platform_lang_impl(ErrorStripeUpdateManager.kt:143)                  	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManager$asyncRepaintErrorStripePanel$1.invokeSuspend(ErrorStripeUpdateManager.kt)                  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:34)                  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)                  	at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)                  	at kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner.<init>(DebugProbesImpl.kt:531)                  	at kotlinx.coroutines.debug.internal.DebugProbesImpl.createOwner(DebugProbesImpl.kt:510)                  	at kotlinx.coroutines.debug.internal.DebugProbesImpl.probeCoroutineCreated$kotlinx_coroutines_core(DebugProbesImpl.kt:497)                  	at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineCreated(DebugProbes.kt:7)                  	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:161)                  	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)                  	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:358)                  	at                  	kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)                   	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:53)                   	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)                   	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:44)                   	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)                   	at com.intellij.codeInsight.daemon.impl.ErrorStripeUpdateManager.launchRepaintErrorStripePanel(ErrorStripeUpdateManager.kt:99)                   	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.repaintErrorStripeAndIcon(DaemonCodeAnalyzerImpl.java:475)                   	at com.intellij.codeInsight.daemon.impl.PassExecutorService.repaintErrorStripeAndIcon(PassExecutorService.java:588)                   	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$5(PassExecutorService.java:538)                   	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)                   	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)                   	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)                   	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport$RunnableUnitFunction.invoke(NestedLocksThreadingSupport.kt:1041)                   	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport$RunnableUnitFunction.invoke(NestedLocksThreadingSupport.kt:1039)                   	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteIntentReadAction(NestedLocksThreadingSupport.kt:707)                   	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:1098)                   	at com.intellij.openapi.application.impl.ApplicationImpl$7.lambda$run$0(ApplicationImpl.java:652)                   	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)                   	at com.intellij.openapi.application.impl
(cherry picked from commit ddfaf9223971040572df1e66c539b340bc2f42f6)

IJ-CR-199845

GitOrigin-RevId: 9b81ac23c3eb7b2fb6d3ef43c002d9b2ba48995e