external build: instead of disabling java extensions automatically suggest user to do it himself if build process failed to start with NoSuchMethodError (IDEA-147368, IDEA-CR-6812)