revert a bit
on IDEA-CR-37916

java.lang.UnsupportedOperationException: memory file system does not support #toFile()
	at com.github.marschall.memoryfilesystem.AbstractPath.toFile(AbstractPath.java:74)
	at com.intellij.util.io.PathKt.exists(path.kt:15)
	at com.intellij.configurationStore.DefaultProjectElementNormalizerKt.writeConfigFile(defaultProjectElementNormalizer.kt:148)