IJPL-174575 NoClassDefFoundError (SkiaLayerAnalytics) fixed
(cherry picked from commit e3f857ead68d7a83671fbc308afa26de636fb23b)


(cherry picked from commit 38f78526dd04f10011439b3ab634733bf09c4ed7)

IJ-MR-155570

GitOrigin-RevId: 098a026a056c8c3da9d27d27f3a3d2c0f2e13864