IJPL-162726 IJent: wrap `WatchService` for `MultiRoutingFileSystem`
It was possible to get original paths from `WatchKey`, and it led to occasional errors like:

```
java.lang.ClassCastException: class sun.nio.fs.WindowsPath cannot be cast to class com.intellij.platform.core.nio.fs.MultiRoutingFsPath (sun.nio.fs.WindowsPath is in module java.base of loader 'bootstrap'; com.intellij.platform.core.nio.fs.MultiRoutingFsPath is in unnamed module of loader 'app')
  at com.intellij.platform.core.nio.fs.MultiRoutingFsPath.unwrap(MultiRoutingFsPath.java:219)
  at com.intellij.platform.core.nio.fs.MultiRoutingFsPath.resolve(MultiRoutingFsPath.java:98)
```


(cherry picked from commit 8ef5a4a5ebdd43649ca99c286bc534484de8ff57)

IJ-CR-148204

GitOrigin-RevId: 24e0691fd0c3cca4b27da5915fc0e3ff4319ddc9