Don't mess with threadLocal variables since threadContext is stored there and resetting the value leads to test failure.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Value was not reset correctly. Expected: InstalledThreadContext(snapshot=null, context=EmptyCoroutineContext), actual: InstalledThreadContext(snapshot=null, context=null)

GitOrigin-RevId: 6025899b23e6451dd5f6da08f03808ec7e571bf7