cleanup [kotlin]: remove unused compile-time dependencies from kotlin modules (IJPL-226455)
These dependencies don't have corresponding dependencies in XML module descriptors, so an attempt to use classes from these dependencies may fail with NoClassDefFoundError.
This is also needed to ensure that these dependencies won't be reported by IdeaUltimatePluginModuleDependenciesTest after improving its logic.

GitOrigin-RevId: 8dc0357fbae7c872e5a914c5ca22b31eeaf97d9e