Fix module name for plugin.xml
This commit fixes:
```
java.lang.IllegalStateException: jpsOutPluginXml=.../out/artifacts/classes/production/kotlin.idea/META-INF/plugin.xml doesn't exist!
```

GitOrigin-RevId: cb1a7927fb3d00efb1159554ecf3ec457d62e415