don't use runBlockingMaybeCancellable if in non-cancellable section
java.lang.IllegalStateException: com.intellij.openapi.progress.CeProcessCanceledException: com.intellij.openapi.progress.IndicatorCancellationException
  at com.intellij.openapi.application.impl.CoroutineExceptionHandlerImpl.handleException(CoroutineExceptionHandlerImpl.kt:26)
  at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:38)
  at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
  at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
  at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:230)
  at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:909)
  at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:866)
  at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
  at kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner.resumeWith(DebugProbesImpl.kt:538)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.openapi.progress.CeProcessCanceledException: com.intellij.openapi.progress.IndicatorCancellationException
  at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:134)
  at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:125)
  at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$3(context.kt:108)
  at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:963)
  at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:106)
  at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
  at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:125)
  at com.intellij.openapi.progress.CoroutinesKt.runBlockingMaybeCancellable(coroutines.kt:152)
  at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:117)
  at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
  at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
  at com.intellij.openapi.vcs.changes.ChangeListManager.getInstance(ChangeListManager.java:27)
  at com.intellij.vcs.changes.ChangeListsScopesProvider.getCustomScopes(ChangeListsScopesProvider.java:35)
  at com.intellij.psi.search.scope.packageSet.CustomScopesProvider.getFilteredScopes(CustomScopesProvider.java:17)
  at com.intellij.psi.search.scope.impl.CustomScopesAggregator.getAllCustomScopes(CustomScopesAggregator.java:20)
  at com.intellij.ui.tabs.FileColorsModel.initPredefinedAndGlobalScopes(FileColorsModel.java:56)
  at com.intellij.ui.tabs.FileColorsModel.<init>(FileColorsModel.java:43)
  at com.intellij.ui.tabs.FileColorManagerImpl.<init>(FileColorManagerImpl.java:45)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
  at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
  at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:961)
  at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
  at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:168)
  at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:147)
  at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:97)
  at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
  at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
  at com.intellij.ui.FileColorManager.getInstance(FileColorManager.java:14)
  at com.intellij.ui.tabs.EditorTabColorProviderImpl.getProjectViewColor(EditorTabColorProviderImpl.java:30)
  at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getFileBackgroundColor(EditorTabPresentationUtil.kt:47)
  at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getFileBackgroundColor(VfsPresentationUtil.java:48)
  at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:22)
  at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:31)
  at com.intellij.ide.util.treeView.AbstractTreeNode.computeBackgroundColor(AbstractTreeNode.java:275)
  at com.intellij.ide.projectView.ProjectViewNode.computeBackgroundColor(ProjectViewNode.java:298)
  at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:87)
  at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
  at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:486)
  at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:467)
  at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:460)
  at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:418)
  at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
  at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
  at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:343)
  at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
  at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
  at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTr

GitOrigin-RevId: 8818915dff7eec53678bfead1da003c1a82c0f38