Eel: fix Provider mismatch: WindowsFileSystemProvider != TracingFileSystemProvider(WindowsFileSystemProvider)
This error appeared in tests:

```
java.lang.IllegalArgumentException: Provider mismatch: sun.nio.fs.WindowsFileSystemProvider@76cf91c9 != TracingFileSystemProvider(sun.nio.fs.WindowsFileSystemProvider@76cf91c9)
	at com.intellij.platform.core.nio.fs.MultiRoutingFileSystemProvider.getDelegate(MultiRoutingFileSystemProvider.java:197)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystemProvider.copy(DelegatingFileSystemProvider.java:198)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at com.intellij.platform.ijent.performance.benchmarks.IJentWslZipFileReadBenchmarkTest$measureReadFile$1.invokeSuspend(IJentWslZipFileReadBenchmarkTest.kt:48)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.intellij.platform.ijent.performance.BenchmarkKt$runIJentBenchmark$1.invokeSuspend(benchmark.kt:42)
Caused by: java.lang.IllegalArgumentException: Provider mismatch: sun.nio.fs.WindowsFileSystemProvider@76cf91c9 != TracingFileSystemProvider(sun.nio.fs.WindowsFileSystemProvider@76cf91c9)
	at com.intellij.platform.core.nio.fs.MultiRoutingFileSystemProvider.getDelegate(MultiRoutingFileSystemProvider.java:197)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystemProvider.copy(DelegatingFileSystemProvider.java:198)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at com.intellij.platform.ijent.performance.benchmarks.IJentWslZipFileReadBenchmarkTest$measureReadFile$1.invokeSuspend(IJentWslZipFileReadBenchmarkTest.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:36)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:112)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.testFramework.common.TimeoutKt.timeoutRunBlocking-rnQQ1Ag(timeout.kt:25)
	at com.intellij.testFramework.common.TimeoutKt.timeoutRunBlocking-rnQQ1Ag$default(timeout.kt:16)
	at com.intellij.platform.ijent.performance.BenchmarkKt.runIJentBenchmark(benchmark.kt:39)
	at com.intellij.platform.ijent.performance.benchmarks.IJentWslZipFileReadBenchmarkTest.measureReadFile(IJentWslZipFileReadBenchmarkTest.kt:30)
	at com.intellij.platform.ijent.performance.benchmarks.IJentWslZipFileReadBenchmarkTest.measureZipFileReading(IJentWslZipFileReadBenchmarkTest.kt:56)
	at com.intellij.platform.ijent.performance.benchmarks.IJentWslZipFileReadBenchmarkTest.java zip file(IJentWslZipFileReadBenchmarkTest.kt:84)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.ide.starter.junit5.CurrentTestMethodArgumentsProvider.intercept(CurrentTestMethodArgumentsProvider.kt:53)
	at com.intellij.ide.starter.junit5.CurrentTestMethodArgumentsProvider.interceptTestTemplateMethod(CurrentTestMethodArgumentsProvider.kt:23)
	at com.intellij.testFramework.junit5.impl.TestLoggerInterceptor.intercept$lambda$0(TestLoggerInterceptor.kt:12)
	at com.intellij.testFramework.TestLoggerKt.recordErrorsLoggedInTheCurrentThreadAndReportThemAsFailures(testLogger.kt:86)
	at com.intellij.testFramework.junit5.impl.TestLoggerInterceptor.intercept(TestLoggerInterceptor.kt:11)
	at com.intellij.testFramework.junit5.impl.AbstractInvocationInterceptor.interceptTestTemplateMethod(AbstractInvocationInterceptor.kt:37)
	at com.intellij.platform.ijent.testFramework.functional.LogTestName.runTest(IjentTestUtil.kt:63)
	at com.intellij.platform.ijent.testFramework.functional.LogTestName.interceptTestTemplateMethod(IjentTestUtil.kt:30)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	```

GitOrigin-RevId: 690ff7ad7dca00f46bf577c8f5819f3e0068b380