[JEWEL-1263] Fix NoClassDefFoundError for JNA in standalone artifact
'net.java.dev.jna:jna' was used by 'StandalonePlatformCursorController'
but missing from the 'jewel-int-ui-standalone' POM, causing a
'NoClassDefFoundError: com/sun/jna/Library' at runtime whenever
'IntUiTheme' was composed.

Signed-off-by: Nebojsa.Vuksic <nebojsa.vuksic@jetbrains.com>