Escape added to prevent 3.6 from error "invalid escape sequence"
  File "_jb_runner_tools.py", line 25
    match = re.match("^(.+)(\(.+\))$", part)                        ^
SyntaxError: invalid escape sequence \(

Fixing PythonUnitTestingTest.testUTRunnerByPattern

(cherry picked from commit 7e9d2ff)