[platform] restore 'protobuf' as a runtime dependency to intellij.platform.ide.impl module (GTW-9738)
It was removed in 124621881da7, but this library is used by zip-signer, and if it isn't added explicitly as a dependency, it isn't included in JetBrains Client distribution, and it fails to download plugins with "java.lang.NoClassDefFoundError: com/google/protobuf/MessageOrBuilder".

GitOrigin-RevId: 0806c619d6f66367899daedb1cfd8f4cc1a70d0c