Kotlin plugin: Move 'kotlinc.kotlin-stdlib' to the top of the classpath
This commit partially fixes:
org.jetbrains.kotlin.idea.references.BuiltInsReferenceResolverTest#testAllReferencesResolved

Failure stacktrace:

  junit.framework.AssertionFailedError: Can't resolve public final infix fun and(other: kotlin.Boolean): kotlin.Boolean defined in kotlin.Boolean[DeserializedSimpleFunctionDescriptor@2097e66d]
    at junit.framework.Assert.fail(Assert.java:57)
    at junit.framework.Assert.assertTrue(Assert.java:22)
    at junit.framework.Assert.assertNotNull(Assert.java:256)
    at junit.framework.TestCase.assertNotNull(TestCase.java:426)
    at org.jetbrains.kotlin.idea.references.BuiltInsReferenceResolverTest.testAllReferencesResolved(BuiltInsReferenceResolverTest.java:74)

 # Investigation details

The test was failing because
`DefaultBuiltIns.getInstance().getBuiltInsPackageScope()` (inside
`org.jetbrains.kotlin.idea.references.BuiltInsReferenceResolverTest#getAllStandardDescriptors`)
loads builtins from the runtime classpath. And `kotlin-stdlib-jdk8`
(which is platform's stable stdlib) was higher in the classpath than
`kotlinc.kotlin-stdlib` (which is Kotlin's bootstrap stdlib).

Some time ago (kotlin/1564f2c549bbdff361c02f71aa128e06274336ce)
`@kotlin.internal.IntrinsicConstEvaluation` was annotated all over
Kotlin's stdlib. The fact that we load old stdlib from classpath, causes
the situation that we are not able find builtins descriptors inside
`DecompiledTextIndex` (because descriptors are stored with a
`IntrinsicConstEvaluation` annotation now)

The test still fails because of KT-53073

 # Notes

* Technically, I could move only `kotlinc.kotlin-stdlib` in
  `kotlin.idea.tests` module to fix the test. But it's more correct to
  move `kotlinc.kotlin-stdlib` to the top for all Kotlin plugin modules
  because this way it's closer to the production environment.
* To be completely fair, it's more correct to move all kotlinc.*
  libraries to the top because it's the way production classpath works.
  But I'm not ready now to commit such a big commit, knowing that Yan
  does big "split modules" refactoring. I hope I will do it later + add
  tests into "project structure tests".

GitOrigin-RevId: c359d16e01608beff7ddf3bc5d9514a241729c3b