[Workspace Model] Do not try to register module components on plugin loading/unloading (registerComponents)
When the new plugin is loaded `registerComponents` is called and legacy bridge tries to register legacy-components again.

Fixes:
SharedIndexesTest.testSharedIndexInvalidationOnIndexVersionChange
SharedIndexesTest.test explicit requestReindex leads to input data recalculation by content

Both tests fail with:
org.picocontainer.PicoRegistrationException: Key com.intellij.workspace.legacyBridge.intellij.LegacyBridgeFilePointerProvider duplicated
  at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
  at com.intellij.serviceContainer.ComponentManagerImpl.registerService(ComponentManagerImpl.kt:551)
  at com.intellij.workspace.legacyBridge.intellij.LegacyBridgeModuleImpl.registerComponents(LegacyBridgeModuleImpl.kt:65)
  at com.intellij.ide.plugins.DynamicPlugins.loadPluginDescriptor(DynamicPlugins.kt:634)

GitOrigin-RevId: 1687338ae67c850f38e949c4be7fa78a1ae4f67e