IJPL-237691 cleanup partially initialized serializers
initSerializers can be interrupted by PCE, so let's clean up state
so that the next try will see no partial garbage

The following exception is an example of a problem that causes partial state:

2026-03-12 19:06:33,620 [   6994]   WARN - #c.i.u.PsiIconUtil - IconProvider org.jetbrains.kotlin.idea.FirKotlinIconProvider@1695926e threw an exception
java.lang.AssertionError: ID: java.METHOD is not unique, but found in both com.intellij.psi.impl.java.stubs.serializers.JavaMethodStubSerializer and com.intellij.psi.impl.java.stubs.serializers.JavaMethodStubSerializer
	at com.intellij.psi.stubs.StubSerializerEnumerator.assignId(StubSerializerEnumerator.java:87)
	at com.intellij.psi.stubs.SerializationManagerImpl.registerSerializer(SerializationManagerImpl.java:199)
	at com.intellij.psi.stubs.SerializationManagerImpl.registerSerializer(SerializationManagerImpl.java:158)
	at com.intellij.psi.stubs.SerializationManagerImpl.doInitSerializedUnderLock(SerializationManagerImpl.java:304)
	at com.intellij.psi.stubs.SerializationManagerImpl.initSerializers(SerializationManagerImpl.java:254)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:221)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:129)

GitOrigin-RevId: 8a15a6c0a0397df80d9de3094b2323e29be401cf