[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed custom model validator

(cherry picked from commit 1ba6f7b7532a7167b2e3b5245bff7000bd91f2e0)

IJ-CR-21961

GitOrigin-RevId: 1df56814d4a2250b4b0e606951f4bc809978704e