[platform] IDEA-346395 fix NoClassDefFoundError for OAuthService
(cherry picked from commit eb1fe1fe02fb7151672c9c7142804ec168412586)

IJ-CR-129496

GitOrigin-RevId: 9d35d95124fd6936ff529e662f3ad4a4634f67cf