git: replace explicit inclusion of Java-related components by optional dependency on Java plugin
This is needed to properly add classloader of Java plugin as a parent classloader for Git plugin to avoid NoClassDefFoundError in Java-related classes from remote-servers-git-java.xml ((IDEA-217879).

GitOrigin-RevId: ef49f80281c4f1c4e38c7fa2365941bd8419829d