postpone project generator UI instantiation to fix blinking test NewProjectWizardTest.testDefaultLanguageLevel
E.g. NodeJsInterpreterField may spawn "node --version" on its creation which leads to
java.lang.AssertionError: Thread leaked: Thread[BaseDataReader: output stream of /opt/nvm/nvm-wrapper/node --version,4,main]; TIMED_WAITING (true)
--- its stacktrace:
 at java.lang.Object.wait(Native Method)
 at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:175)
 at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
 at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
 at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

(cherry picked from commit d613252)
https://upsource.jetbrains.com/IDEA/review/IDEA-CR-26443