[rdct] fix error from test "OpenAPI modules must not depend on implementation-detail libraries"
junit.framework.AssertionFailedError: OpenAPI module 'intellij.platform.kernel' depends on 'kotlinx-serialization-core' library.
This dependency is not used in this module.

GitOrigin-RevId: e95b76991c741ed493756759663bfc539a1ed54a