[kotlin] Pack compiler plugins into separate JARs (KTIJ-21201)
Before 2022.1, IntelliJ repository used parts of the Kotlin plugin for compilation. The following JAR files were added into the JPS process classpath:

- jps/kotlin-jps-plugin.jar
- kotlin-plugin.jar
- kotlin-common.jar

The whole contents of these JARs was also available to the Kotlin compiler. As all compiler plugins were packed inside 'kotlin-plugin.jar', 'kotlinx.serialization' used in some IntelliJ modules was loaded from there, instead of the location specified in '-Xplugin'.

However, 'kotlin-plugin.jar' doesn't include dependent compiler classes, such as 'ComponentRegistrar' (as they are in 'kotlinc_kotlin-compiler-common.jar' and 'kotlinc_kotlin-compiler-fe10.jar'), so 'NoClassDefFoundError' occurred during compilation.

GitOrigin-RevId: 57d71652a1110cd9a73e6397ea60425be371c085