Fix Code With Me tests after Kotlin plugin being migrated to PluginLayout
Test example: com.jetbrains.warmup.tests.WarmupTest

Failure stacktrace:
```
java.lang.IllegalStateException: /home/bobko/jb/intellij/out/artifacts/KotlinPlugin/kotlinc doesn't exist
	at com.intellij.tools.launch.impl.ClassPathBuilder.build(ClassPathBuilder.kt:50)
	at com.intellij.tools.launch.Launcher.launch(Launcher.kt:21)
	at com.jetbrains.thinclient.testFramework.launch.ProcessLauncher.launchServer(ProcessLauncher.kt:74)
	at com.jetbrains.thinclient.testFramework.testBase.DistributedTestBase$startWarmup$1.invoke(DistributedTestBase.kt:177)
	at com.jetbrains.thinclient.testFramework.testBase.DistributedTestBase$startWarmup$1.invoke(DistributedTestBase.kt:55)
```

(cherry picked from commit 274e0410864a83b0f6759d84c6648eefaf2b9b7d)

GitOrigin-RevId: 5d0c05b74fee5100fda4da1bd627685bdac427d8