jps-build-script-dependencies upgraded to 211.6085 to fix java.lang.NoSuchMethodError: 'void com.intellij.util.concurrency.AppExecutorUtil.shutdownApplicationScheduledExecutorService()'
(cherry picked from commit 449a647dde347a05950813bb5b3d8d73e1f15dc9)

IJ-CR-5987

GitOrigin-RevId: 36190d1b6e7e36f22a6919da593477737cae316b