Fix for changes in JUnit 4.12-SNAPSHOT (should also work with earlier versions of JUnit).
* org.junit.runners.Suite.getChildren now returns Collections.unmodifiableList instead of List.
This is an issue since IDEA's junit plugin could try to remove a child while iterating:
java.lang.UnsupportedOperationException
    at java.util.Collections$UnmodifiableCollection$1.remove(Collections.java:1012)
    at com.intellij.junit4.IdeaSuite.getChildren(IdeaSuite.java:97)

* org.junit.runners.ParentRunner.getFilteredChildren now returns Collection instead of List (method is private).
java.lang.ClassCastException: java.util.Collections$UnmodifiableCollection cannot be cast to java.util.List
    at com.intellij.junit4.IdeaSuite.getDescription(IdeaSuite.java:55)