Fix wizard in FIR plugin for 212 platform
This commit fixes:
```
    java.lang.IllegalArgumentException: Missing extension point: com.intellij.newProjectWizard.buildSystem.kotlin in container Application (containerState=COMPONENT_CREATED)  (Internal)
    	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:252)
    	at com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28)
    	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
    	at org.jetbrains.kotlin.tools.projectWizard.KotlinSettings$buildSystems$1.invoke(KotlinNewProjectWizard.kt:60)
    	at org.jetbrains.kotlin.tools.projectWizard.KotlinSettings$buildSystems$1.invoke(KotlinNewProjectWizard.kt:56)
```

GitOrigin-RevId: c19461fd603078f0e157d2c7f61426b4bdb74532