Remove plugin references that are not part of CE
The Django one causes the following kaboom after running test suites in
community edition:

    java.lang.ClassNotFoundException: com.jetbrains.django.testRunner.DjangoTestTestIdUrlProvider: java.lang.ClassNotFoundException: com.jetbrains.django.testRunner.DjangoTestTestIdUrlProvider
    com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: java.lang.ClassNotFoundException: com.jetbrains.django.testRunner.DjangoTestTestIdUrlProvider
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:99)
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:122)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:244)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
        at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
        at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
        at com.intellij.execution.testframework.sm.CompositeTestLocationProvider.getLocation(CompositeTestLocationProvider.java:50)
        at com.intellij.execution.testframework.sm.runner.SMTestProxy.getLocation(SMTestProxy.java:261)

The `duplicates.profile` just turns red but thankfully has not yet caused any
exceptions