[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed custom model validator

(cherry picked from commit 1ba6f7b7532a7167b2e3b5245bff7000bd91f2e0)

IJ-CR-21961

GitOrigin-RevId: 7e41ab37396e44539507298753b4f3bd4b7747a8