IJPL-339 fix blinking tests
Fixes the following exception by replacing RefValueHashMap#containsKey with RefValueHashMap#get

ERROR: containsKey() makes no sense for weak/soft map because GC can clear the value any moment now
com.intellij.util.IncorrectOperationException: containsKey() makes no sense for weak/soft map because GC can clear the value any moment now
	at com.intellij.util.containers.RefValueHashMapUtil.pointlessContainsKey(RefValueHashMapUtil.java:13)
	at com.intellij.util.containers.RefValueHashMap.containsKey(RefValueHashMap.java:90)
	at com.intellij.psi.impl.file.impl.ManyItemMap.remove(FileProviderMap.kt:360)
	at com.intellij.psi.impl.file.impl.FileProviderMapImpl.remove(FileProviderMap.kt:208)

GitOrigin-RevId: 490e02086d448bacf68840af0365569980b91f42