GitPushNativeResult.java: fix NPE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'where' of com/intellij/openapi/util/text/StringUtil.containsIgnoreCase must not be null
	at com.intellij.openapi.util.text.StringUtil.$$$reportNull$$$0(StringUtil.java)
	at com.intellij.openapi.util.text.StringUtil.containsIgnoreCase(StringUtil.java)
	at git4idea.push.GitPushNativeResult.isNonFFUpdate(GitPushNativeResult.java:67)
	at git4idea.push.GitPushRepoResult.convertType(GitPushRepoResult.java:134)


(cherry picked from commit ded691d7711fff4106f6dcb7dd13b303c928edb2)

IJ-CR-141906

GitOrigin-RevId: 661f3779cd22ffef5034944d7ab726ba0e5b7aef