[Kotlin UI DSL] Restored some API because of incompatibility
-  Product:PhpStorm 231.4840.331 Plugin: Projector 1.11.0
Caused by: java.lang.NoSuchMethodError: 'com.intellij.ui.layout.CellBuilder com.intellij.ui.layout.RowBuilderWithButtonGroupProperty.radioButton$default(com.intellij.ui.layout.RowBuilderWithButtonGroupProperty, com.intellij.ui.layout.Row, java.lang.String, java.lang.Object, java.lang.String, int, java.lang.Object)'

GitOrigin-RevId: 85d89bef9e9e36ba3fe0af4630bc281d879da70e