do not create default project on app dispose
To avoid exceptions on exit like:
java.lang.RuntimeException: Memory leak detected: 'com.intellij.openapi.vfs.encoding.EncodingManagerImpl@695b8c2c' of class com.intellij.openapi.vfs.encoding.EncodingManagerImpl
See the cause for the corresponding Disposer.register() stacktrace:

(cherry picked from commit c5cb87e3f59db99203ad5b3d7d224f387098b84b)