[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed role hint

(cherry picked from commit bbc5bc5d8116179005930786bc246db11eada6a4)

IJ-CR-21961

GitOrigin-RevId: 5b3778e39eb5dd912409b3d3ba7a89bcf4a7b6af