Update module_redeclarator.py
In my system I have both PyQt4 and PyQt5, they run using different sip versions so when trying to import PyQt4 it will crash raising a runtime error like:
RuntimeError: the sip module implements API v11.0 but the PyQt4.QtGui module req
uires API v9.1

This halts any generation of PyQt5 skeletons also which is bad.

Also, the code _initializeQApp will return if PyQt4 can be loaded and a QCoreApplication instance created and thus leaving out PyQt5 generation.

Breaking these up in two cases (qt4 and qt5) solves the partial issue of not generating qt5-skeletons but still qt4-skeletons isnt generated due to the sip-version problem.

I will try and look into this a bit more but would gladly accept some more input/help in resolving the issue.