[maven] IDEA-364046 Maven 4.0.0-rc-1 in Maven40PluginDependenciesResolver, retry plugin resolution twice
There seems to be a race condition in plugin resolution as of Maven 4.0.0-rc1, which leads to

There seems to be a race condition in plugin resolution as of Maven 4.0.0-rc1, which leads to

org.apache.maven.plugin.PluginResolutionException: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.4 or one of its dependencies could not be resolved:
    Could not transfer artifact org.apache.maven:maven-model:jar:2.2.0 from/to central-mirror (https://cache-redirector.jetbrains.com/repo1.maven.org/maven2): /mnt/cache/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
    in DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:242)
    Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.apache.maven:maven-model:jar:2.2.0 (absent): Could not transfer artifact org.apache.maven:maven-model:jar:2.2.0 from/to central-mirror (https://cache-redirector.jetbrains.com/repo1.maven.org/maven2): /mnt/cache/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
    in DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:305)
    ... 23 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache.maven:maven-model:jar:2.2.0 (absent): Could not transfer artifact org.apache.maven:maven-model:jar:2.2.0 from/to central-mirror (https://cache-redirector.jetbrains.com/repo1.maven.org/maven2): /mnt/cache/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
    in DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
    ... 24 more
    Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven:maven-model:jar:2.2.0 from/to central-mirror (https://cache-redirector.jetbrains.com/repo1.maven.org/maven2): /mnt/cache/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
    in ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44)
    ... 3 more
    Caused by: java.nio.file.NoSuchFileException: /mnt/cache/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
    in UnixException.translateToIOException(UnixException.java:92)

GitOrigin-RevId: c13a52c9ca8703a3a269191b78ce5bff1306d23b