IJPL-339 fix PIEAE in execution: ensure location is valid before passing it
fixes the following exception

2025-08-12 08:32:31,190 [ 126875] SEVERE - #c.i.e.a.PreferredProducerFind - Element: class org.intellij.plugins.markdown.lang.psi.impl.MarkdownFile #Markdown  because: different providers: org.intellij.plugins.markdown.xml.DefaultMarkdownFileViewProvider{vFile=file:///mnt/agent/temp/buildTmp/testl9ip3fqdczw0n/ide-tests/cache/projects/unpacked/grails_3/README.md, vFileId=35, content=VirtualFileContent{size=2427}, eventSystemEnabled=true}(39bd658a); null(0)
invalidated at: see attachment [Plugin: org.intellij.plugins.markdown] [Plugin: Tomcat]
com.intellij.diagnostic.PluginException: Element: class org.intellij.plugins.markdown.lang.psi.impl.MarkdownFile #Markdown  because: different providers: org.intellij.plugins.markdown.xml.DefaultMarkdownFileViewProvider{vFile=file:///mnt/agent/temp/buildTmp/testl9ip3fqdczw0n/ide-tests/cache/projects/unpacked/grails_3/README.md, vFileId=35, content=VirtualFileContent{size=2427}, eventSystemEnabled=true}(39bd658a); null(0)
invalidated at: see attachment [Plugin: org.intellij.plugins.markdown] [Plugin: Tomcat]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:100)
	at com.intellij.execution.actions.PreferredProducerFind.findAllProducers(PreferredProducerFind.java:74)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:114)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:103)
	at com.intellij.execution.actions.ConfigurationContext.createConfigurationsFromContext(ConfigurationContext.java:428)
	at com.intellij.execution.actions.ExecutorAction.getRunConfigsForCurrentFile(ExecutorAction.java:313)
	at com.intellij.execution.actions.ExecutorAction.getRunCurrentFileActionStatus(ExecutorAction.java:251)
	at com.intellij.execution.actions.ExecutorAction.getRunCurrentFileActionStatus(ExecutorAction.java:228)
	at com.intellij.execution.actions.ExecutorAction.update(ExecutorAction.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction$lambda$2(ActionUtil.kt:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction(ActionUtil.kt:273)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1$1.invoke(ActionUpdater.kt:526)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1$1.invoke(ActionUpdater.kt:525)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$2$1.invoke(ActionUpdater.kt:146)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:111)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:101)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunReadAction(NestedLocksThreadingSupport.kt:844)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1206)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3(cancellableReadAction.kt:28)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:303)
	at com.intellij.concurrency.ThreadContext.installThreadContext$default(threadContext.kt:301)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:24)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:100)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:86)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invokeSuspend(InternalReadAction.kt:35)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:285)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:34)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:56)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionUndispatched(coroutines.kt:81)
	at com.intellij.openapi.application.CoroutinesKt.readActionUndispatched(coroutines.kt:68)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invokeSuspend(trace.kt:114)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.kt:923)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$callAction(ActionUpdater.kt:76)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invokeSuspend(ActionUpdater.kt:525)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invokeSuspend(ActionUpdater.kt:922)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateAction(ActionUpdater.kt:976)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.kt:368)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$expandGroupChild(ActionUpdater.kt:76)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$doExpandActionGroup$2$expandResult$1$1.invokeSuspend(ActionUpdater.kt:287)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:610)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runDefaultDispatcherTask(CoroutineScheduler.kt:1194)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:906)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:775)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:762)
Caused by: com.intellij.diagnostic.PluginException: Element: class org.intellij.plugins.markdown.lang.psi.impl.MarkdownFile #Markdown  because: different providers: org.intellij.plugins.markdown.xml.DefaultMarkdownFileViewProvider{vFile=file:///mnt/agent/temp/buildTmp/testl9ip3fqdczw0n/ide-tests/cache/projects/unpacked/grails_3/README.md, vFileId=35, content=VirtualFileContent{size=2427}, eventSystemEnabled=true}(39bd658a); null(0)
invalidated at: see attachment [Plugin: org.intellij.plugins.markdown]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:100)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:508)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:107)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:77)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:71)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:67)
	at com.intellij.psi.SmartPointerManager.createPointer(SmartPointerManager.java:30)
	at com.intellij.execution.junit.RuntimeConfigurationProducer.storeSourceElement(RuntimeConfigurationProducer.java:80)
	at com.intellij.javaee.appServers.run.configuration.J2EEConfigurationProducer.createConfigurationByElement(J2EEConfigurationProducer.java:48)
	at com.intellij.execution.junit.RuntimeConfigurationProducer.createProducer(RuntimeConfigurationProducer.java:48)
	at com.intellij.execution.actions.PreferredProducerFind.findAllProducers(PreferredProducerFind.java:68)
	... 68 more
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class org.intellij.plugins.markdown.lang.psi.impl.MarkdownFile #Markdown  because: different providers: org.intellij.plugins.markdown.xml.DefaultMarkdownFileViewProvider{vFile=file:///mnt/agent/temp/buildTmp/testl9ip3fqdczw0n/ide-tests/cache/projects/unpacked/grails_3/README.md, vFileId=35, content=VirtualFileContent{size=2427}, eventSystemEnabled=true}(39bd658a); null(0)
invalidated at: see attachment
	... 78 more

GitOrigin-RevId: ccc1a61857870e8229f12bce1036fe69bc28b404