Revert "Import bazel tests module to tools/idea."
Build errors:
VmTraceParserTest.java:351:
cannot find symbol
return TestResources.getFile(getClass(), path);

This reverts commit 3c0d55764bf973f16b66c4030dfd63b359c53885.

Change-Id: Ifb01788d5a23b4c4dac2fb93fda828f28c7240e2