IJPL-238 fix lack of commons-lang3 in test classpath
java.lang.RuntimeException: Cannot execute com.intellij.idea.Main: Error reported from child process logger: java.lang.reflect.InvocationTargetException
  at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1393)
  at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1368)
  at com.intellij.util.ui.EdtInvocationManager$SwingEdtInvocationManager.invokeAndWait(EdtInvocationManager.java:102)
  at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:83)
  at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:111)
  at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:89)
  at com.intellij.ide.bootstrap.ApplicationLoader.executeApplicationStarter$lambda$0(ApplicationLoader.kt:302)
  at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2084)
  at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020)
  at org.languagetool.rules.spelling.CachingWordListLoader.loadWords(CachingWordListLoader.java:63)

GitOrigin-RevId: f108821ce6e24cd5d7fbb15e53e8d36a7e00880f