IDEA-162545 Error:gradle-resources-test:project: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
(cherry picked from commit ad2d368)