build scripts: a second attempt to call the `runApplicationStarter` method is added
as a hacky workaround for various sporadic exceptions from the IDE side like:
> com.intellij.util.IncorrectOperationException: Sorry but parent has already been disposed so the child will never be disposed


(cherry picked from commit 3fec80344f1498694021d0878190c3864d858379)

IJ-CR-169585

GitOrigin-RevId: de147b22ab30743788317a591624d6dd57f205d3