[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed version compare

(cherry picked from commit ceed0e8209cd6770393faf1aed5d34a65d597340)

IJ-CR-21961

GitOrigin-RevId: 07baa25ea6dba31b342bf3238a0fb162adc89b88