kotlin.base.plugin shouldn't depend on intellij.maven & intellij.gradle.common
kotlin.base.plugin shouldn't know anything about Maven & Gradle. Convert
the needed functionality into ExtensionPoint.

This commit fixes:

    java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/settings/GradleSettings
        at org.jetbrains.kotlin.idea.compiler.configuration.KotlinArtifactsDownloader.failedToDownloadUnbundledJpsMavenArtifact(KotlinArtifactsDownloader.kt:217)
        at org.jetbrains.kotlin.idea.compiler.configuration.KotlinArtifactsDownloader.lazyDownloadMissingJpsPluginDependencies(KotlinArtifactsDownloader.kt:74)
        at org.jetbrains.kotlin.idea.jps.SetupKotlinJpsPluginBeforeCompileTask.execute(SetupKotlinJpsPluginBeforeCompileTask.kt:24)

Reproducible only when IDEA run via dev server

GitOrigin-RevId: 4fbff5155d98d3a1948d7736200b7c0343fadb82