cleanup pycharm: drop obsolete standalone python plugin building
current code is not working anyway, because:
error: SNAPSHOT.0 is not a correct version
and also jps-bootstrap is not working for a some time

GitOrigin-RevId: e439ddc125c6d272981cc954f7eeb621027a7545