IDEA-CR-50687: IDEA-218940 java.lang.NoClassDefFoundError: com/intellij/util/ui/JBScalableIcon when installing plugin built with 2019.2 in pre-2019.2 IDE
(cherry picked from commit 8edb0fbbe675f41ff68396f44578be5905d3692a)

GitOrigin-RevId: 506f1ae582b1b4f32ab434b1db063033a2a35845