[Gradle|Exec] new: introduce API for the simple reflective calling of removed setters and getters in Gradle API
This API ignores all reflection method access exception, because we can identify in which Gradle version this public API was removed.

### Issues
  * IDEA-369597 Cannot debug test with gradle. NoSuchMethodError: org.gradle.api.tasks.testing.Test.setForkEvery


(cherry picked from commit 069ed7531f58751c56ab91d1c3483facd0c041eb)

IJ-CR-161042

GitOrigin-RevId: 4447a1f4bdd8d9ff6a02ae847fdc9d72c69e47a4