IJPL-194051 Eel+WSL: catch more exceptions in `EelWslMrfsBackend`
Service initialization can throw not only `AlreadyDisposedException` but also `ProcessCanceledException` at least this way:

```
com.intellij.openapi.progress.ProcessCanceledException: com.intellij.platform.instanceContainer.internal.ContainerDisposedException: Container 'ApplicationImpl@876093454 services' was disposed
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:699)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:672)
    at com.intellij.execution.wsl.WslIjentAvailabilityService$Companion.getInstance(WslIjentAvailabilityService.kt:28)
    at com.intellij.platform.ide.impl.wsl.EelWslMrfsBackend.compute(WslEelProvider.kt:65)
```

Catching `CancellationException` is error-prone because of the "silent killer", even though there are no coroutines in this code. Therefore, there's a check for the other common ancestor of `ProcessCanceledException` and `AlreadyDisposedException`.

GitOrigin-RevId: 7a02041fd4d6af47d3b6029f9f2ff3b565a682a9