PicoException: fix javadoc refs
(cherry picked from commit c76b4331600cc491e94b9d897412351b96b28b1e) IDEA-CR-68672

GitOrigin-RevId: 38f84062016759dbdf7c11a4232ccd9a56292e26