fix PY-14472 Matplotlib import has failed in Python Console (AttributeError: 'module' object has no attribute 'rcParams')
(cherry picked from commit 3781bd3aca1e82b0ccdb73b90ad8e1ae7ae023be)