253-eval-backport
[aia-eval] LME-1007 GEMINI runner for eval (proper ACP integrated)

Merge-request: IJ-MR-197416
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
(cherry picked from commit 106b135277e9592e7da86e7924a8532ebda19a48)

[aia-eval] LME-1006 Move trace input attribute to Zenml

Merge-request: IJ-MR-197202
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
(cherry picked from commit 1d82a48ae9de8b7311045dd1e3bd8c639b2888c6)

[aia-eval] LME-1001 PyCharm Again: all python evals are failing with NoSuchMethodError: PyProjectSdkConfiguration.setReadyToUseSdk

(cherry picked from commit 57f18085e941f69c17c1ee8bff2e95960779a38e)

[aia-eval] LME-990 setSelectedAgentAuth(DEFAULT_ACP_AGENT_ID, AcpAgentAuthentication.AGENT)

Change ACP plugin visibility from 'private' to 'internal'

Merge-request: IJ-MR-196325
Merged-by: Nikolai Gruzinov <nikolai.gruzinov@jetbrains.com>
(cherry picked from commit fa26bf4346e1db50e398b1f8a8b5df00eeb51205)

[aia-eval] LME-977 CLAUDE_CODE uses new agent.id

Merge-request: IJ-MR-195808
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>

(cherry picked from commit 5ddc118f43247462b99f3d867a21f1e81081d615)

IJ-MR-195105

(cherry picked from commit 7829f95074c0d90e8ed03d2b733811c4c2da8e78)

[aia] AIML-2 remove llm judge from llm judge eval plugin in favor to zenml side

(cherry picked from commit 3191481eeee399f97710813376289266adaf50d7)

[aia-eval] LME-938 ACP agents also can work via JBAI (so no native keys are provided)

Merge-request: IJ-MR-195030
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
(cherry picked from commit 7b2c8c56d96037dae18f998ca1e82de2056cd6d9)

[aia-eval] LME-943 Configure OpenCode via ACP in IDE. change runner id name

(cherry picked from commit 4999b24449829d41b3ddcfb915a956af294ca2a1)

[aia-eval] LME-937 Configure Junie via ACP in IDEA. extend CodeGenerationSweRunnerType with acp junie, claude, open code

(cherry picked from commit 706b7f9e4992f53acb48e3d98fba838e629d8346)

[aia-eval] LME-923 Switch to USD for quota metrics in eval

[aia-eval] LME-923 Too many zeros

[aia-eval] LME-923 Renaming the metric names

[aia-eval] LME-923 Switch to USD for quota metrics in eval

Merge-request: IJ-MR-194449
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
(cherry picked from commit a81d362a9d29893183c9b4c9ccf8f15da6be0db9)

[aia-eval] LME-912 don't assert GEMINI_API_KEY for GEMINI_ACP runner

Merge-request: IJ-MR-194251
Merged-by: Nikolai Gruzinov <nikolai.gruzinov@jetbrains.com>
(cherry picked from commit 208d5d36d2e55240ca93bfba8d7c5581ee28758d)

[aia-eval] LME-907 Skip reporting quota via COST field

Merge-request: IJ-MR-194048
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
(cherry picked from commit bf88e06655d3e5cf4071219bcf9c61e35d09245f)

[evaluation-plugin] LME-935 Read a file using VFS

Merge-request: IJ-MR-194028
Merged-by: Roman Vasiliev <Roman.Vasiliev@jetbrains.com>
(cherry picked from commit 5d1f75de079369c1b29b825f0f9b9c21cf8830c4)

[aia-eval] LME-779 Configure Python "SWE-Bench Pro" dataset

(cherry picked from commit 1d54d089acd64eff71584ada206633a1119836bd)

LME-793 LME-863 ACP client and git file tracking

Merge-request: IJ-MR-193308
Merged-by: Roman Vasiliev <Roman.Vasiliev@jetbrains.com>
(cherry picked from commit 74e878f658ba7995f2e74576fe5c524843ba4b7c)

[evaluation-plugin] LME-863 Configure gemini-cli to work in SWE-like evaluations

Merge-request: IJ-MR-191230
Merged-by: Roman Vasiliev <Roman.Vasiliev@jetbrains.com>
(cherry picked from commit 6d50518bfaf8f1c6481ca928b68b046b5f9ffcf9)

LLM-20945 add METHOD_QUALIFIED_NAME_PROPERTY to tests

Space-RevId: 4230b7e7d1be7ea7d5235566697c417e57cef454
(cherry picked from commit 59f1433170976548717f1b77f6486c9a55b16c49)

[aia] LLM-20945 remove explicit dependency on K2 and add on `intellij.kotlin.plugin.community.main` instead

Space-RevId: d5f2d91359ae430c2a36c11e93c2abf042b915c4
(cherry picked from commit efb24e24fe594e453200f43ced66f8b16dd065e0)

[aia] LLM-20945 rename callGraph packages to be consistent with `IntellijProjectPackageNameTest`

Space-RevId: e0f0a56e04a47319bc6ae82ba047455aac7657ff
(cherry picked from commit 0026747deb4761fbae51561ccb1d8facc661b597)

[aia] LLM-20945 fix cases when textRange of psiElement is not defined

Space-RevId: d2e5031e397cc044159763d57583984f43167fe5
(cherry picked from commit f88c553932aaa42a26d577cba3fe148ba6e80d8b)

[aia] LLM-17686 post-merge-fix

Space-RevId: 1efb8045b2bac38b2eef389142eb89ae4d09db61
(cherry picked from commit 3eb9bc87e8c0c8b913a1ad6fad0797050f58823d)

[aia] LLM-17686 bazel upd

Space-RevId: 494b23688216913eea51fc5c93c6022b71c5cd09
(cherry picked from commit e586ce848d90b154d60b67bdf16aac84b62a57d6)

[aia] LLM-17686 post-rebase fixes

Space-RevId: 9f360a67b0a7213eb729250360e4a560c896cce1
(cherry picked from commit 2e81a8c24ce7f97ba7e2f5df5e111571d0e9b4f3)

[aia] LLM-17686 basel upd

Space-RevId: 70d2d4e1c269834228f0fc85eb29c24e03b049eb
(cherry picked from commit 6f4ad55ff67ae5f3795e629ca68addd56709d414)

[aia] LLM-17686 refactor: unify test data directory handling

Space-RevId: d070f4b781e7156406a92738aa00be36cc0c0b47
(cherry picked from commit fe377c966aab7066c0841e3968b1b48f4b463086)

[aia] LLM-17686 refactor: move common logic from `JavaCallGraphBuilderTest` and `KotlinCallGraphBuilderTest` to `CallGraphBuilderTestUtil`

Space-RevId: fb95ddf91c051f64986ba77fa892d32e885ee32b
(cherry picked from commit 08135590e004aaad4404a4acd7c3e60a115b9b93)

[aia] LLM-17686 commit missing test

Space-RevId: 5049d900d7acfe9e5b783fdfd6b9d1fcf9aec53d
(cherry picked from commit 62b7f4e10ce1654d5607326d6539024078a23f6a)

[aia] LLM-17686 fix java call graph builder when qualified name is null for some reason

Space-RevId: 09a83e8f6ebffebad320f42562a58e0c18f5165f
(cherry picked from commit 8cfc1dbfd7f0d2a742ad8f475b1abd23a0066a0d)

[aia] LLM-17686 fix call graph builder with qualified names

Space-RevId: bb64edcaf214e1162a6e572feae09b33beca82ee
(cherry picked from commit b41cd6d668dbb485d8f5c3a6bc14f403f77359ae)

[aia] LLM-17686 add more cases with kdocs and interfaces and inner function in KotlinCallGraphBuilderTest

Space-RevId: 1d537b21666b7474e8698f6c3e997a56cf07ba02
(cherry picked from commit 9b83910354ff99c42a71a339355ed4268fbdc50b)

[aia] LLM-17686 update KotlinCallGraphBuilderTest for parameterized tests

Space-RevId: c0f307847ac30e4701d23eabd174ff192bea06c2
(cherry picked from commit a88af2082b7b4677f621b281c596f81283541c0f)

[aia] LLM-17686 remove @Test annotaton in JUnit3

Space-RevId: 27a87ae2084f1f25852087fea06727b2438b4b9d
(cherry picked from commit cce03e01d6a7ccb56e3b3185b49c2df012aa3866)

[aia] LLM-17686 refactor progress bar utilities

Space-RevId: 8cc29bc62806ea70797787f5c423eaa6fb7d0366
(cherry picked from commit a24ea44758722dcd4c1b8dbf976c0f615aacb693)

[aia] LLM-17686 extend call graph building with project roots

Space-RevId: e3d23248a4e7e35124d133215fbc841a48312ad1
(cherry picked from commit 3fda0942e60258b2bb811d2ba4cc0b1ea3b17ca6)

[aia] LLM-17686 compare all constructed graphs in tests

Space-RevId: 283ce8b84118be402244fbdaa18806b6dbfa4019
(cherry picked from commit f1ee68292ed51df4a12efe5d093e1c5d89f0ca79)

[aia] LLM-17686 fix ids in JavaCallGraphBuilder.kt

Space-RevId: 103be4b7b724a7012a8cee087c743c7013a3c4c5
(cherry picked from commit 7773473122321676c8366d4749a369cae297ed2d)

[aia] LLM-17686 cleanup

Space-RevId: 42aa05c4d332cc3c7c326545b6f2386ec1fee62f
(cherry picked from commit 1534268208cd993bd281422be3f9b12e14c5c32b)

[aia] LLM-17686 fix BuildCallGraphCommand.kt

Space-RevId: 8e03804a6876cbbfdadc10ee91fb7905751ff821
(cherry picked from commit 7db4baf9e13de092d8033f4973979394ab8f4a8f)

[aia] LLM-17686 add finding through extension points

Space-RevId: fc83746c64527818afc73293794ece1a83055b78
(cherry picked from commit c009f533765510989657b4b9a083df184d30d2e3)

[aia] LLM-17686 take only main reference

Space-RevId: 1ea2dddb4fb134faf6c63dd4c59dee7dae0c8332
(cherry picked from commit 8e0ace00469ac6330dc008ee5793837cc8e2d6e1)

[aia] LLM-17686 replace KotlinChatCodeGenerationVisitor with KotlinCallGraphBuilder

Space-RevId: 6e06bb8cb77d3fdd63dc04ef7889a2393cbdd2b3
(cherry picked from commit 7f84be9fdfb5ab2a3ff63ef129ec5455c1e1e852)

[aia] LLM-17686 refactor CallGraph handling and restructure plugin

Refactored the CallGraph implementation, extracting definitions and Java-specific handling into separate modules. Introduced tests for Java call graph building and expanded test scenarios to improve coverage.

Space-RevId: 8cbc04cb697a3c6ed9a41ad4a7b2d155b81aff41
(cherry picked from commit c8b0ddcb1560848bb0681185030e75abe9cc03b2)

[aia] LLM-17686 basel upd

Space-RevId: fae71bfca61e9a674826185a6f1168a05e67d469
(cherry picked from commit 0845dfeaf44fd00d837adf343c090adb36d8e05a)

[aia] LLM-17686 fix serialisation: make compatible with a python pipeline

Space-RevId: d7991de76782c5bca0da2b59b718f775cf816c47
(cherry picked from commit 1c231cc8aebebec8a37cd4dda2aa2cd8d1ac10de)

[aia] LLM-17686 mapNotNull

Space-RevId: d818434afb800ae04c13e4fcf635bb05b8862800
(cherry picked from commit c5acc6dab2766c1101d8e399a6eb5cd4e83f7e4f)

[aia] LLM-17686 refactor CallGraph serialization and skip nodes and edges if data is missing

Space-RevId: c5990d9f3d5db241b761b20229ea6d1da504f73f
(cherry picked from commit 0eac3e7a61ce806997b113517577d97265ac9b5e)

[aia] LLM-17686 add CallGraphEvaluationCommand

Space-RevId: 3a9e58bb81f46db2412ec9ebcadb2a3043425289
(cherry picked from commit 4201377d97835f8569691817371f0491998ac801)

[aia] LLM-17686 separate `CallGraphBuilder` implementation with wrapping the `EvaluationVisitor`; add tests

Space-RevId: 9631d90e3d517d146c856026de293978e2fb77a9
(cherry picked from commit 58fd039f9a4edc198dffde13a21c1ff9798f4744)

[evaluation] IJPL-220714 Move Evaluation Dataset toolwindow to an internal action

Space-RevId: c04c6bcbfa7f93e77976c0154b1d39177d1ea6aa
(cherry picked from commit a72baf1e95364871131dd07e43629bc7725120ba)


Co-authored-by: Anton Spilnyy <Anton.Spilnyy@jetbrains.com>
Co-authored-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>
Co-authored-by: Nikolai Gruzinov <nikolai.gruzinov@jetbrains.com>
Co-authored-by: Nikolai Palchikov <nikolai.palchikov@jetbrains.com>
Co-authored-by: Roman Vasiliev <Roman.Vasiliev@jetbrains.com>

Merge-request: IJ-MR-197694
Merged-by: Nikolai Bogdanov <nikolai.bogdanov@jetbrains.com>

GitOrigin-RevId: 6f0d7ef80476a2215f6876c441ae7b805a48f219