IJPL-149248: Add the missing dependency to intellij.libraries.grpc.netty.shaded module
NettyChannelProvider from intellij.libraries.grpc.netty.shaded is a subclass of ManagedChannelProvider from intellij.libraries.grpc
Without this fix, PluginException: Cannot load class io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider is thrown caused by NoClassDefFoundError: io/grpc/ManagedChannelProvider.

GitOrigin-RevId: 11881a7c425ba959119ab4280ba067b305f4f803