IJPL-238954 Maven: remove dependency from intellij.maven to intellij.maven.server.telemetry module
`intellij.maven.server.telemetry` module isn't added to the IDE's classpath. The dependency `intellij.maven` on it worked because it was used only when running from source code with a single classloader. However, such a configuration is fragile, one may easily start using classes from other code and get `NoClassDefFoundError` at runtime. Now MavenServerTelemetryClasspathUtil class is moved to `intellij.maven` module and the dependency is removed.

This change is necessary to enable checks for dependencies in *.iml file pointing to modules not present in the distribution (IJPL-238954).

GitOrigin-RevId: 62e0533beb5401413d3287bc8b17945d122c53b5