Downgrade Kotlin compiler version
RC version was causing `I’m getting java.lang.NoSuchMethodError: ‘org.jetbrains.kotlin.ir.expressions.impl.IrSetFieldImpl org.jetbrains.kotlin.ir.builders.ExpressionHelpersKt.irSetField(org.jetbrains.kotlin.ir.builders.IrBuilderWithScope, org.jetbrains.kotlin.ir.expressions.IrExpression, org.jetbrains.kotlin.ir.declarations.IrField, org.jetbrains.kotlin.ir.expressions.IrExpression` for some colleagues

GitOrigin-RevId: 54f7ced0d0e9b8ab8525871eb5707329782476ee