icon sync: okhttp library compile time dependency:
** Syncing icons..
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/MediaType
	at org.jetbrains.intellij.build.images.sync.TeamCityKt.<clinit>(teamCity.kt:18)
	at org.jetbrains.intellij.build.images.sync.Context.<init>(Context.kt:104)
	at org.jetbrains.intellij.build.images.sync.Context.<init>(Context.kt:16)
	at org.jetbrains.intellij.build.images.sync.CheckIconsKt.checkIcons$default(checkIcons.kt:18)
	at org.jetbrains.intellij.build.images.sync.IdeaSyncFromIconsRepoKt.main(ideaSyncFromIconsRepo.kt:18)
Caused by: java.lang.ClassNotFoundException: okhttp3.MediaType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

GitOrigin-RevId: 93d0fc8ae5c9f0df781bb64f7a0f6622656a7608