IJPL-194226 IJent: catch `IjentUnavailableException` via `CoroutineExceptionHandler`
This is the third attempt to fix the issue.
1. The commit fca1360aab7946592afe7c83328790956ef2ce40 was supposed to fix it, but the catch-block didn't help.
2. The commit e093800ad2051b2d19fd3ce33da73bc1a29abb46 tried to check a hypothesis that a wrong class of `IjentUnavailableException` is caught. The hypothesis turned out to be false, there were no specific error messages.

The actual problem is that the error is logged not by the `java.lang.Thread` exception handler, even though the stacktrace points on it:
```
ERROR: Uncaught exception. Context=[Kernel@sri80l3ko12471ugkob4, Rete(abortOnError=false, commands=capacity=2147483647,data=[onReceive], reteState=kotlinx.coroutines.flow.StateFlowImpl@5b6d8ec0, dbSource=ReteDbSource(reteState=kotlinx.coroutines.flow.StateFlowImpl@5b6d8ec0)), DbSourceContextElement(kernel Kernel@sri80l3ko12471ugkob4), ComponentManager(ApplicationImpl@1363734584), com.intellij.codeWithMe.ClientIdContextElementPrecursor@30e72d1c, CoroutineName(com.intellij.platform.ide.impl.wsl.ProductionWslIjentManager), CoroutineId(1149), "com.intellij.platform.ide.impl.wsl.ProductionWslIjentManager#1149":StandaloneCoroutine{Cancelling}@4f0c9d0, Dispatchers.Default]
com.intellij.platform.ijent.IjentUnavailableException$CommunicationFailure: The process IjentId(ijent-0-wsl-u2004-rvm) suddenly exited with the code -1
  at com.intellij.platform.ijent.spi.IjentSessionProcessMediatorKt.ijentProcessExitAwaiter(IjentSessionProcessMediator.kt:147)
  ...
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at com.intellij.platform.ijent.spi.IjentThreadPool$IjentThreadFactory$newThread$thread$1.run(IjentThreadPool.kt:68)
```

The error message "Uncaught exception. Context=" is written by `fleet.util.async.UncaughtCoroutineExceptionHandler`.

This commit overrides the coroutine exception handler from Fleet's to a custom one that ignored `IjentUnavailableException`.

GitOrigin-RevId: 7c66e8904fa4b8c0a4ec4c9d4e992b24debb2923