IndexNotReadyException: put dumb mode start trace in the cause, not in suppressed
Because suppressed exceptions do not play well with the EA, and now all the INRE are automatically recognized as caused by the DumbService

GitOrigin-RevId: 233d19238a7b9f77cfda3617dc4b4b1d80b4f6cd