[kotlin] Replace `junit-jupiter-engine` with `junit-jupiter` in new Kotlin project/module poms
KTIJ-30077 Maven: New kotlin project cannot run tests

Cherry-pick with edits of KTIJ-27045 Maven: "NoClassDefFoundError" with 'junit-jupiter-engine' default dependency

(cherry picked from commit 6b34dae4f13eadc0bc76e27c4f4dd44eef2cff84)

IJ-MR-135636

GitOrigin-RevId: 2b73e19016b4ddd522504ae6feb845034dcffa21