[kotlin] Always load kotlin.Result$Companion from the platform classloader (KTIJ-22623)
Starting from the 1.8.0-dev-2355 bootstrap, the Kotlin compiler generates 'InnerClasses' class attributes, as required by the JVM specification (see KT-27936). Such attributes reference nested classes as 'Class_info'-typed constant pool entries. It means the nested class names appeared also in the constant pool.

It turns out that 'ClasspathInferer' from the Gradle Tooling API relies on constant pool of model dependency classes (such as 'NoArgModel'). Unlike 'kotlin.Result' itself, 'ClasspathInferer' loads the 'kotlin.Result$Companion' class from the Kotlin plugin, as it's not mentioned in the exception list in 'PluginClassLoader'. It ends with the following error:

LinkageError: loader constraint violation: loader com.intellij.ide.plugins.cl.PluginClassLoader @252dbe45 wants to load class kotlin.Result$Companion. A different class with the same name was previously loaded by com.intellij.util.lang.PathClassLoader @769c9116. (kotlin.Result$Companion is in unnamed module of loader com.intellij.util.lang.PathClassLoader @769c9116)

The fix makes all known nested classes inside the 'kotlin.Result' to load in the same class loader as the 'kotlin.Result' itself.

GitOrigin-RevId: 1815c42de9f8c8e683569a70fc2fe94fd0d55d82