[settings] IJPL-250481: fix NoClassDefFoundError for MacFullScreenSupport on Linux/Windows
MacFullScreenSupport was instantiated eagerly, triggering Class.forName on all
platforms and crashing on Linux/Windows due to the missing com.apple.eawt classes.
Replaced with a lazy lambda


(cherry picked from commit 23e49d1be1641ae3e8b2a5e0a21aa9226303e327)

IJ-CR-217470

GitOrigin-RevId: a7aae081dbf2224c7494c7f41d89072585a89e06