OC-21807: add trace logging to catch who closes a popup
idea.log will contain the stack trace with `#com.intellij.ui.popup.AbstractPopup:trace`:
2021-06-23 01:13:50,194 [18543812]  TRACE - ntellij.ui.popup.AbstractPopup -
java.lang.Exception: cancel popup stack trace
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:745)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:727)
	at com.intellij.ui.LightweightHint.hide(LightweightHint.java:376)
	at com.intellij.ui.LightweightHint.hide(LightweightHint.java:366)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.doHide(LookupImpl.java:1110)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.hideLookup(LookupImpl.java:1096)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.hide(LookupImpl.java:1087)
	at com.intellij.codeInsight.hint.HintManagerImpl.hideHints(HintManagerImpl.java:1001)
	at com.intellij.codeInsight.hint.EscapeHandler.doExecute(EscapeHandler.java:33)

(cherry picked from commit 41f904bc79a2e4e4362463c2112435f13fb7e5ac)

IJ-CR-10590

GitOrigin-RevId: f4f44ba6ffd354be44d18061c9d8dfaaca472772