Refactoring: convert local class into inner class due to bug in incremental kotlin compiler
The bug manifests itself in tests (e.g. com.intellij.java.codeInsight.ParameterInfoTest): runtime types are weired and do not match compile time types, and all this is happening in kotlinc-generated code which does not even exist in physical files on-the-disk

java.lang.ClassCastException: class com.intellij.util.indexing.UnindexedFilesFinder cannot be cast to class com.intellij.util.indexing.roots.IndexableFilesIterator (com.intellij.util.indexing.UnindexedFilesFinder and com.intellij.util.indexing.roots.IndexableFilesIterator are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @5c072e3f)
  at com.intellij.util.indexing.PerProjectIndexingQueue$addFiles$1$1.invoke(PerProjectIndexingQueue.kt:152)
  at com.intellij.util.indexing.PerProjectIndexingQueue.addFiles$lambda$1$lambda$0(PerProjectIndexingQueue.kt:152)
  at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
  at com.intellij.util.indexing.PerProjectIndexingQueue.addFiles(PerProjectIndexingQueue.kt:152)
  at com.intellij.util.indexing.PerProjectIndexingQueue.access$addFiles(PerProjectIndexingQueue.kt:103)
  at com.intellij.util.indexing.PerProjectIndexingQueue$sinkFactory$1.commit(PerProjectIndexingQueue.kt:122)
  at com.intellij.util.indexing.PerProviderSinkFactory$PerProviderSinkImpl.commit(PerProjectIndexingQueue.kt:67)
  ...

GitOrigin-RevId: 46a0fc13f8b1fa72b38477e0334f0ec05f0e964b