[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fix model interpolation - support new maven component ModelVersionProcessor

(cherry picked from commit 6b788a0952b5af76c4ed472de14e5319be7e71c1)

IJ-CR-21961

GitOrigin-RevId: cb31f5613d5206cf829c55022197d3ab3080b4c4