IOException: Updates to symlinks not supported
Windows is not case sensitive, but the updater assumes this is a symlink
C:\users\{userid}\AppData\mytemp\PackageOperation03\unzip\m2repository\com->
C:\Users\{userid}\AppData\mytemp\PackageOperation03\unzip\m2repository\com
(C:\users vs c:\Users with capital U)

java.io.IOException: Updates to symlinks not supported
	at com.intellij.updater.UpdateAction.doBuildPatchFile(UpdateAction.java:24)
	at com.intellij.updater.BaseUpdateAction.buildPatchFile(BaseUpdateAction.java:46)
	at com.intellij.updater.PatchFileCreator.create(PatchFileCreator.java:36)
	at com.android.tools.idea.sdk.updater.PatchGenerator.generateFullPackage(PatchGenerator.java:112)

Change-Id: Ib7cf68b52335b49febb60eb4aa0f9ac2dded86d7