`AccessDeniedException` on Win. when building IDE.
`sourceZipFile` is an opened stream of the file, which `transformZipUsingTempFile` tries to move data to.

This call fails:
```kotlin
 Files.move(tempFile, file, StandardCopyOption.REPLACE_EXISTING)
 ```
 because `file` is blocked by `sourceZipFile`.

 This isn't a problem on **nix, but on Windows opened files are blocked by default, hence `AccessDenied`:

 ```
    java.nio.file.AccessDeniedException: C:\intellij_master\community\out\pycharm-ce\dist.all\plugins\completionMlRanking\lib\completionMlRanking.jar
    	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
    	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:392)
    	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
    	at java.base/java.nio.file.Files.move(Files.java:1432)
    	at org.jetbrains.intellij.build.io.ZipFileWriterKt.transformZipUsingTempFile(ZipFileWriter.kt:41)
    	at org.jetbrains.intellij.build.ClasspathKt.reorderJar(classpath.kt:131)
    	at org.jetbrains.intellij.build.ClasspathKt$reorderJar$$inlined$use$default$1.invokeSuspend(span.kt:53)
    	at org.jetbrains.intellij.build.ClasspathKt$reorderJar$$inlined$use$default$1.invoke(span.kt)
    	at org.jetbrains.intellij.build.ClasspathKt$reorderJar$$inlined$use$default$1.invoke(span.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
    	at org.jetbrains.intellij.build.ClasspathKt.reorderJar(classpath.kt:315)
    	at org.jetbrains.intellij.build.impl.JarPackagerKt$buildJars$list$1$1$1.invokeSuspend(JarPackager.kt:864)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
    	Suppressed: java.nio.file.AccessDeniedException: C:\intellij_master\community\out\pycharm-ce\dist.all\lib\annotations.jar
```

We moved `sourceZip` lower to make it closed before `move`

GitOrigin-RevId: 14535191d061e88d36e7eb46a46f0c89db2fe133