CWM: UsageViewManager: Annotate parameter 'factory' as @Nullable
Fixes IAE when attempting to open usages in a toolwindow:

    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.jetbrains.rdserver.findUsages.BackendUsageViewManager.showUsages, parameter factory

This happens when CWM is installed.

GitOrigin-RevId: 7046e365dc3ff3a726b14203bffc0f6e9536d0e4