[Gradle|Exec] fix: call the setForEvery(Long) function for debugging in old Gradle environment
The setForEvery function's argument was changed from Long to long in Gradle 8.1. It caused precompiled code failure on older Gradle versions, because it tries to execute the setForkEvery(long) function that doesn't exist on old Gradle versions.

### Issues
  * IDEA-369597 Cannot debug test with gradle. NoSuchMethodError: org.gradle.api.tasks.testing.Test.setForkEvery

GitOrigin-RevId: 333c0be2030f25e62f7e2af735dee3a11066f760