[platform] IDEA-346395 fix NoClassDefFoundError for OAuthService
(cherry picked from commit eb1fe1fe02fb7151672c9c7142804ec168412586)

IJ-CR-129496

GitOrigin-RevId: c30d99814819978dc86b5849f06c3e9121dfc032