[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fixed version compare

(cherry picked from commit ceed0e8209cd6770393faf1aed5d34a65d597340)

IJ-CR-21961

GitOrigin-RevId: 3ea25451cf97e7ba373281b8e30043b8639c0873