fixed PY-12476 Django: Nose Test Runner: not able to run django tests with django 1.6: AttributeError: 'NoOptions' object has no attribute 'with_fixture_bundling'
(cherry picked from commit 8e237e07575e26697695696102b33fda19a5a75f)