Fix `java.util.MissingResourceException` for resources from KotlinBundleIndependent
Test example: `org.jetbrains.kotlin.findUsages.FindUsagesTestGenerated.Kotlin.Conventions.Components#testCallableReferences`

This was broken by e30f09d513b1c39731b30d97d911533856ae79eb

Stacktrace:
```
java.util.MissingResourceException: Can't find bundle for base name messages.KotlinBundleIndependent, locale en_US

    at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
    at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
    at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
    at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
    at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:156)
    at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:143)
    at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:131)
    at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:117)
    at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:110)
    at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:46)
    at org.jetbrains.kotlin.idea.KotlinBundleIndependent.message(KotlinBundleIndependent.kt:16)
    at org.jetbrains.kotlin.idea.findUsages.KotlinFindUsagesHandlerFactory.createFindUsagesHandler(KotlinFindUsagesHandlerFactory.kt:89)
    at com.intellij.find.findUsages.FindUsagesHandlerFactory.createFindUsagesHandler(FindUsagesHandlerFactory.java:42)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:171)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:164)
...
```

GitOrigin-RevId: 0ea602d21cda6133a7b43643990cf728c3e42b49