IJPL-218636 [psi] fix tree event for `childRemoved`
instead of oldParent/newParent, there must be parent installed.
See the corresponding stacktrace:

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'child' of com/intellij/codeInsight/daemon/impl/PsiChangeHandler.queueElement must not be null
  at com.intellij.codeInsight.daemon.impl.PsiChangeHandler.$$$reportNull$$$0(PsiChangeHandler.java)
  at com.intellij.codeInsight.daemon.impl.PsiChangeHandler.queueElement(PsiChangeHandler.java)
  at com.intellij.codeInsight.daemon.impl.PsiChangeHandler.childRemoved(PsiChangeHandler.java:121)
  at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:509)
  at com.intellij.psi.impl.PsiManagerImpl.lambda$fireEvent$9(PsiManagerImpl.java:448)
  at com.intellij.psi.impl.PsiManagerImpl.runWriteActionOnEdtRegardlessOfCurrentThread(PsiManagerImpl.java:467)
  at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:446)
  at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:334)
  at com.intellij.psi.impl.file.impl.PsiVFSListener.filesMoved$lambda$0(PsiVFSListener.kt:586)
  at com.intellij.psi.ExternalChangeActionUtil$PsiExternalChangeService.withExternalChange(ExternalChangeActionUtil.kt:59)
  at com.intellij.psi.ExternalChangeActionUtil.externalChangeAction$lambda$0(ExternalChangeActionUtil.kt:28)
  at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:124)
  at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:124)
  at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteAction(NestedLocksThreadingSupport.kt:999)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1132)
  at com.intellij.psi.impl.file.impl.PsiVFSListener.filesMoved(PsiVFSListener.kt:552)

GitOrigin-RevId: 64101f296637f1c6702d0fdbd16e4f9fc0eb66f3