diagnostics for NPE
NullPointerException: Cannot invoke "com.intellij.codeInspection.ex.LocalInspectionToolWrapper.getTool()" because "toolWrapper" is null
  at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createHighlightsForDescriptor(LocalInspectionsPass.java:261)

GitOrigin-RevId: 1c7e05111f03ce7dd183a14659f0e88e884b4dc6