.idea/jarRepositories.xml: add missing repository in community
This commit fixes in intellij-community:
```
Error resolving dependencies for intellij.platform.util:
java.lang.RuntimeException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.jetbrains.intellij.deps:log4j:jar:1.2.17.1 in central (https://cache-redirector.jetbrains.com/maven-central):
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.jetbrains.intellij.deps:log4j:jar:1.2.17.1 in central (https://cache-redirector.jetbrains.com/maven-central):
Could not find artifact org.jetbrains.intellij.deps:log4j:jar:1.2.17.1 in central (https://cache-redirector.jetbrains.com/maven-central)
```

GitOrigin-RevId: 99b83a1fc31150ff45b8ccf9d13cee7dfe6b5e69