Exclude long-running thread used by webDeployment from the thread-leak check
This fixes com.jetbrains.plugins.webDeployment.tests.UploadTest with
UploadMode.WITH_HONEST_COLLECTION_PHASE.

Without the fix tests were failing with assertion:

java.lang.AssertionError: Thread leaked: Thread[org.apache.commons.vfs2.cache.SoftRefFilesCache$ReleaseThread,4,main] (alive) WAITING
--- its stacktrace:
 at java.base@17.0.12/java.lang.Object.wait(Native Method)
 at java.base@17.0.12/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 at org.apache.commons.vfs2.cache.SoftRefFilesCache$ReleaseThread.run(SoftRefFilesCache.java:54)
---


(cherry picked from commit 01e4400350cbed79e89945b3b37d74a285a710ee)

IJ-CR-169127

GitOrigin-RevId: 3a4d7d2a3dbae4b14c4c36554aa6d68ee4fc19e0