PasswordSafeException: add deprecation javadoc
(cherry picked from commit 5a8415f75e2bb42798e957b497366dbd3d5c92e0) IDEA-CR-54940

GitOrigin-RevId: 59cda5baaffb2d6df9fcb8df6c4fac603f4172c2