AlreadyDisposedException: add javadoc link to Disposable
(cherry picked from commit 76891d2b0aab4cdb1ac419dbd4694daa382930a7)

IJ-CR-18026

GitOrigin-RevId: 652ff44989a75636c066e009806ad0ae3f7aeaf3