[git] Wrap the VcsException not to loose the cause
Before the stacktrace was taken from the processTerminated and was
rather useless:
VcsException: fatal: bad object b97d4813424a4e75ee1a17c0f2de772359bde26e
	at git4idea.commands.GitSimpleHandler$1.processTerminated
	at sun.reflect.GeneratedMethodAccessor39.invoke
	<...>
	at com.intellij.util.EventDispatcher.dispatch
	at git4idea.commands.GitTextHandler$1.processTerminated
	<...>
	com.intellij.execution.process.ProcessWaitFor$1.run

The fix is to show the stack trace of the code which actually called
the command which failed with exception.