Fix that macros contributed by `ProjectWidePathMacroContributor` don't replace paths
^KTIJ-21366 Fixed

Changes in KotlinBundledPathMacroContributor are necessary because
otherwise tests fail with:
```
org.jdom.JDOMException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
  at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:240)
  at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:269)
  at org.jetbrains.kotlin.idea.macros.KotlinBundledPathMacroContributor.getProjectPathMacros(KotlinBundledPathMacroContributor.kt:31)
```
test example: `CustomKotlinCompilerReferenceTest6#test sub and super types`

GitOrigin-RevId: f4811b642b8e6d743e5b6c0721eb26af0f58fde3