BaseExtensionPointName: Add descriptive error message for tests
Suggest a fix for a (misconfigured) JUnit5 test class missing
the `@TestApplication` annotation, in which case the test would
otherwise fail with a rather cryptic NPE error:

    java.lang.NullPointerException: null cannot be cast to non-null type com.intellij.openapi.extensions.impl.ExtensionsAreaImpl

GitOrigin-RevId: 7306e538829a8d9608b3dc48173b438066ef7422