[kotlin] Revert kotlinc.kotlin-stdlib to 1.8.0-dev-1681
Gradle import fails with 1.8.0-dev-2355 for some reason. The current hypothesis: logic for constant pool generation has changed in newest version of the compiler, and 'org.gradle.tooling.internal.provider.serialization.ClasspathInferer.find' traverses class files in some different order.

Error message:

LinkageError: loader constraint violation: loader com.intellij.ide.plugins.cl.PluginClassLoader @252dbe45 wants to load class kotlin.Result$Companion. A different class with the same name was previously loaded by com.intellij.util.lang.PathClassLoader @769c9116. (kotlin.Result$Companion is in unnamed module of loader com.intellij.util.lang.PathClassLoader @769c9116)

GitOrigin-RevId: d16677dfbbc6b1b638f1a38aad5d9a47f685b168