IDEA-140208 java.lang.NoSuchMethodError: org.eclipse.aether.RepositorySystem.newResolutionRepositories(Lorg/eclipse/aether/RepositorySystemSession;Ljava/util/List;)Ljava/util/List; (cherry picked from commit 382196b)