[JEWEL-1263] Fix NoClassDefFoundError for JNA in standalone artifact
'net.java.dev.jna:jna' was used by 'StandalonePlatformCursorController'
but missing from the 'jewel-int-ui-standalone' POM, causing a
'NoClassDefFoundError: com/sun/jna/Library' at runtime whenever
'IntUiTheme' was composed.

Signed-off-by: Nebojsa.Vuksic <nebojsa.vuksic@jetbrains.com>

closes https://github.com/JetBrains/intellij-community/pull/3436

(cherry picked from commit 42c3908fd1a30eb4340e6f8c01f36b910286fd5e)


(cherry picked from commit adfd453d83ffad5d535d33ad7d704506b20effae)

IJ-MR-193916

GitOrigin-RevId: d2be938eebb7b310b279885fade12446c58f2ec3