mps-platform project: patch Kotlin version
Kotlin version 1.2.0 RC used in Idea Community
leads to compilation error:
mps-platform/community/plugins/gradle/src/org/jetbrains/plugins/gradle/service/resolve/GradleIdeaSettingsContributor.kt:80:
Super calls to Java default methods are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'

As quick fix - switch to previous version.

GitOrigin-RevId: a3c81ce38a89cbc0ee0ad193c63e1998245c31e8