[maven] IDEA-290419 Maven 3.8.5 : NoSuchMethodError
fix model interpolation - support new maven component ModelVersionProcessor

(cherry picked from commit 6b788a0952b5af76c4ed472de14e5319be7e71c1)

IJ-CR-21961

GitOrigin-RevId: 4e7fb672948be8a2f33eca27bea974fa752baf9a