vcs: fix recursive update of vcs toolwindow contents
Fix regression after 7dcfe887bfc34c51fad37f49058b10a8c618eaa7

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
....
at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.addContent(ChangesViewContentManager.kt:122)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateContent(VcsToolWindowFactory.kt:95)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateContentIfCreated(VcsToolWindowFactory.kt:84)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateState(VcsToolWindowFactory.kt:68)
at com.intellij.openapi.vcs.changes.ui.ChangesViewToolWindowFactory.updateState(ChangesViewToolWindowFactory.kt:37)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory$getContentManagerListener$1.contentAdded(VcsToolWindowFactory.kt:121)
....
at com.intellij.ui.content.impl.ContentManagerImpl.fireContentAdded(ContentManagerImpl.java:553)
....
at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.addContent(ChangesViewContentManager.kt:122)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateContent(VcsToolWindowFactory.kt:95)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateContentIfCreated(VcsToolWindowFactory.kt:84)
at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateState(VcsToolWindowFactory.kt:68)
at com.intellij.openapi.vcs.changes.ui.ChangesViewToolWindowFactory.updateState(ChangesViewToolWindowFactory.kt:37)
....

GitOrigin-RevId: 4ec782601e83ba9cefe75ea1317126c166fc18a2