PY-56370 No plots with Matplotlib 3.6.0: `AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
Add dummy support for the new pyplot API

(cherry picked from commit a57cfa1a3cd05b211f02eb22bb703fa5ad72404a)

IJ-CR-95901

GitOrigin-RevId: 73f39d1900cf9fbacdde231667a96fc5abc3deeb