add Jgoodies to distributions to fix RUBY-28535 java.lang.NoClassDefFoundError when Create Step Definition action is invoked (cherry-picked from 71e530906482586489447c20b68335cfef479b69)
(cherry picked from commit 2a319a05900002a258cea04be3698e9f64c4dc6f)

GitOrigin-RevId: 6424e034f317d378ffedd588db85068fc9517473