Fix module name for plugin.xml
This commit fixes:
```
java.lang.IllegalStateException: jpsOutPluginXml=.../out/artifacts/classes/production/kotlin.idea/META-INF/plugin.xml doesn't exist!
```

GitOrigin-RevId: f9b26eb2257ffe953ed033cd3f5c35f6590188a7