[^sergey.evdokimov] IDEA-84141 Starting Groovy Shell throws a NoClassDefFoundError if pom.xml references groovy as dependency (cherry picked from commit 0bc97aa)