StartupAbortedException: handle NPE
handle NPE when PluginException.getCause() == null
this NPE leads to program hang since it never properly exists AWT thread

GitOrigin-RevId: fd38e04f81607353835551b2a9fa271f5a840e56