initialize myVFileToViewProviderMap and myTempProviders before registering listeners
This fixes ProjectJdkEelTest.sdks are identifiable by their name in different views

The problem was that the event happens earlier than myVFileToViewProviderMap is initialized, thus causing an NPE

The exception:

java.lang.NullPointerException: Cannot invoke "com.intellij.psi.impl.file.impl.FileViewProviderCache.forEach(com.intellij.psi.impl.file.impl.FileViewProviderCache$CacheEntryConsumer)" because "this.myVFileToViewProviderMap" is null
  at com.intellij.psi.impl.file.impl.FileManagerImpl.possiblyInvalidatePhysicalPsi(FileManagerImpl.java:444)
  at com.intellij.psi.impl.file.impl.FileManagerImpl.lambda$processFileTypesChanged$9(FileManagerImpl.java:425)
  at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:114)
  at com.intellij.openapi.application.impl.AppImplKt$runnableUnitFunction$1.invoke(appImpl.kt:114)
  at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteAction(NestedLocksThreadingSupport.kt:926)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1100)
  at com.intellij.psi.impl.file.impl.FileManagerImpl.lambda$processFileTypesChanged$10(FileManagerImpl.java:420)
  at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:548)
  at com.intellij.psi.impl.file.impl.FileManagerImpl.processFileTypesChanged(FileManagerImpl.java:418)
  at com.intellij.psi.impl.file.impl.FileManagerImpl$1.exitDumbMode(FileManagerImpl.java:79)
  at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:815)
  at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:762)
  ... 70 more
  at com.intellij.testFramework.junit5.impl.TestUncaughtExceptionHandler.assertAllExceptionAreCaught(TestUncaughtExceptionHandler.kt:30)
  at com.intellij.testFramework.junit5.impl.UncaughtExceptionExtension.afterEach(UncaughtExceptionExtension.kt:25)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

GitOrigin-RevId: 992ccf2710a5cb6785fe4e7afa0f2459e6c71565