Debugger outputs many spurious messages regarding: AttributeError: 'DataFrame' object has no attribute 'shape'
An assumption that a DataFrame is only from pandas results in many of the following warning messages and also causes the interactive debugger not to work well when using libraries other than pandas containing a DataFrame class. This is particularly noticeable when debugging pyspark.

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 284, in frame_vars_to_xml
    xml += var_to_xml(v, str(k), evaluate_full_value=eval_full_val)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 384, in var_to_xml
    xml_shape = ' shape="%s"' % make_valid_xml_value(str(v.shape))
  File "/usr/local/Cellar/apache-spark/2.4.0/libexec/python/pyspark/sql/dataframe.py", line 1300, in __getattr__
    "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
AttributeError: 'DataFrame' object has no attribute 'shape'
Unexpected error, recovered safely.
```