Revert "leaking timer threads in MacOSXPreferencesFile"
This reverts commit b26ddd93b9731babc7dde94b766dd3fcc8e35bdb.

This change caused PlatformTestCase.setUp to fail in Bazel:

  java.util.prefs.BackingStoreException: Couldn't get file lock.
    at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:730)
    at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
    at com.intellij.testFramework.ThreadTracker.<clinit>(ThreadTracker.java:116)

Change-Id: I3d0329bde4c22f8d1350314761941ae66ac1cc79